<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="csvml" nsURI="http://csvml/1.0" nsPrefix="csvml">
  <eClassifiers xsi:type="ecore:EClass" name="FileDefinitionSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filedefinitions" upperBound="-1"
        eType="#//FileDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fielddefinitions" lowerBound="1"
        upperBound="-1" eType="#//FieldDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDefinition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FieldType" eType="#//FieldTypTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FieldTypTypes">
    <eLiterals name="String"/>
    <eLiterals name="Integer" value="1"/>
    <eLiterals name="Boolean" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticField" eSuperTypes="#//FieldDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedField" eSuperTypes="#//FieldDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticField" eSuperTypes="#//FieldDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationField" eSuperTypes="#//FieldDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AggregationType" eType="#//AggregationTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedfields" lowerBound="1"
        upperBound="-1" eType="#//FieldDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="#//FieldDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleBasedField" eSuperTypes="#//FieldDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationTypes">
    <eLiterals name="sum"/>
    <eLiterals name="average" value="1"/>
    <eLiterals name="minimum" value="2"/>
    <eLiterals name="maximum" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ResultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonRule" eSuperTypes="#//Rule.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeRule" eSuperTypes="#//Rule.1"/>
</ecore:EPackage>
